volumes:
  larixon_local_redis_data: {}
  larixon_local_postgres_data: {}
  larixon_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: larixon_local_django
    container_name: larixon_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  redis:
    image: docker.io/redis:6
    container_name: larixon_local_redis
    volumes:
      - larixon_local_redis_data:/data

  postgres:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    image: larixon_local_postgres
    container_name: larixon_local_postgres
    volumes:
      - larixon_local_postgres_data:/var/lib/postgresql/data
      - larixon_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  flower:
    <<: *django
    image: larixon_local_flower
    container_name: larixon_local_flower
    ports:
      - '5555:5555'
    command: /start-flower

  celerybeat:
    <<: *django
    image: larixon_local_celerybeat
    container_name: larixon_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  celeryworker:
    <<: *django
    image: larixon_local_celeryworker
    container_name: larixon_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker
