# Generated by Django 5.0.7 on 2024-08-03 14:54

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('modified_at', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Modified At')),
                ('is_removed', models.BooleanField(default=False, verbose_name='Is Removed')),
                ('ip_address', models.GenericIPAddressField(db_index=True, verbose_name='IP Address')),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adverts.advert', verbose_name='Advert')),
            ],
            options={
                'verbose_name': 'Advert View',
                'verbose_name_plural': 'Advert Views',
            },
        ),
    ]
